# Generated by Django 2.2.2 on 2019-06-17 23:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='title_afr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='title_eng',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='title_nso',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='title_por',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='title_sot',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='title_spa',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='title_tsn',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='title_xho',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='title_zul',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Folder'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_afr',
            field=models.TextField(null=True, verbose_name='Text of Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_eng',
            field=models.TextField(null=True, verbose_name='Text of Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_nso',
            field=models.TextField(null=True, verbose_name='Text of Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_por',
            field=models.TextField(null=True, verbose_name='Text of Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_sot',
            field=models.TextField(null=True, verbose_name='Text of Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_spa',
            field=models.TextField(null=True, verbose_name='Text of Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_tsn',
            field=models.TextField(null=True, verbose_name='Text of Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_xho',
            field=models.TextField(null=True, verbose_name='Text of Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_zul',
            field=models.TextField(null=True, verbose_name='Text of Question'),
        ),
        migrations.AddField(
            model_name='resource',
            name='body_afr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='body_eng',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='body_nso',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='body_por',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='body_sot',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='body_spa',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='body_tsn',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='body_xho',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='body_zul',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_afr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_eng',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_nso',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_por',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_sot',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_spa',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_tsn',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_xho',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_zul',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Resource'),
        ),
    ]
