# Generated by Django 2.2.2 on 2019-06-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='title_afr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_eng',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_nso',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_por',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_sot',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_spa',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_tsn',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_xho',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Template'),
        ),
        migrations.AddField(
            model_name='template',
            name='title_zul',
            field=models.CharField(max_length=255, null=True, verbose_name='Title of Template'),
        ),
    ]
